[project]
name = "bitcoin-lending-protocol"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.counter]
# path = "contracts/counter.clar"
# epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

[contracts.lending-pool-v2]
path = "contracts/lending-pool-v2.clar"
epoch = "3.3"
clarity_version = 3

[contracts.passkey-signer-v2]
path = "contracts/auth/passkey-signer-v2.clar"
epoch = "3.3"
clarity_version = 3

[contracts.protocol-governance-v2]
path = "contracts/governance/protocol-governance-v2.clar"
epoch = "3.3"
clarity_version = 3

[contracts.simple-liquidator-v2]
path = "contracts/liquidators/simple-liquidator-v2.clar"
epoch = "3.3"
clarity_version = 3

[contracts.price-oracle-v2]
path = "contracts/oracle/price-oracle-v2.clar"
epoch = "3.3"
clarity_version = 3

[contracts.liquidator-trait-v2]
path = "contracts/traits/liquidator-trait-v2.clar"
epoch = "3.3"
clarity_version = 3

[contracts.lending-pool-v2-trait]
path = "contracts/traits/lending-pool-v2-trait.clar"
epoch = "3.3"
clarity_version = 3

[contracts.math-helpers-v2]
path = "contracts/utils/math-helpers-v2.clar"
epoch = "3.3"
clarity_version = 3

[contracts.test-ref-v2]
path = "contracts/test-ref-v2.clar"
epoch = "3.3"
clarity_version = 3

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet

